# Generated by Django 5.2.2 on 2025-06-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(choices=[('American', 'American'), ('Brazilian', 'Brazilian'), ('British', 'British'), ('Canadian', 'Canadian'), ('Australian', 'Australian'), ('French', 'French'), ('German', 'German'), ('Spanish', 'Spanish'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Other', 'Other')], default='Brazilian', max_length=100)),
            ],
        ),
    ]
